version: '3.7'
services:
  composer:
    build:
      context: ./deps/story-tools-composer
      args:
        - DEPLOYMENT=production
    image: quay.io/mapstory/composer
    command: --no-op
    networks:
      internal:
    expose:
      - "9090"

  pgadmin:
    build: ./docker/pgadmin
    image: quay.io/mapstory/pgadmin
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      internal:
    expose:
      - "5050"

  elasticsearch:
    image: elasticsearch:1.6
    networks:
      internal:
    expose:
      - "9200"

  rabbitmq:
    build: ./docker/rabbitmq
    image: quay.io/mapstory/rabbitmq
    networks:
      internal:
    expose:
      - "15671"
      - "15672"

  django:
    build: .
    image: quay.io/mapstory/django
    depends_on:
      - django_volumes
      - pgadmin
    links:
      - elasticsearch
      - rabbitmq
    volumes:
      - mapstory_media:/var/lib/mapstory/media/
      - mapstory_static:/var/lib/mapstory/static/
    networks:
      internal:
    expose:
      - "8000"

  celery:
    image: quay.io/mapstory/django
    depends_on:
      - django_volumes
    links:
      - elasticsearch
      - rabbitmq
    command: --celery
    volumes:
      - mapstory_media:/var/lib/mapstory/media/
      - mapstory_static:/var/lib/mapstory/static/
    networks:
      internal:
    expose:
      - "8000"

  django_volumes:
    image: quay.io/mapstory/django
    user: root
    entrypoint: /bin/sh -c "chown -R mapstory:mapstory /var/lib/mapstory"
    volumes:
      - mapstory_media:/var/lib/mapstory/media/
      - mapstory_static:/var/lib/mapstory/static/

  geoserver:
    image: quay.io/mapstory/geoserver:2.12.4-1.2
    volumes:
      - geoserver:/var/lib/geoserver
    environment:
      - GEOSERVER_CONTACT_ORG=MapStory
      - GEOSERVER_CONTACT_PERSON=MapStory
      - GEOSERVER_CONTACT_EMAIL=info@mapstory.org
    networks:
      internal:
    expose:
      - "8080"

  nginx:
    build: ./docker/nginx
    image: quay.io/mapstory/nginx
    depends_on:
      - celery
      - composer
    links:
      - django
      - geoserver
    volumes:
      - mapstory_media:/var/lib/mapstory/media/:ro
      - mapstory_static:/var/lib/mapstory/static/:ro
    environment:
      - NGINX_NUM_WORKERS=2
      - NGINX_GZIP_COMP_LEVEL=4
      - NGINX_FILE_CACHE_ENABLED=False
      - NGINX_CLIENT_MAX_BODY_SIZE=500m
    networks:
      internal:
    expose:
      - "80"
      - "443"
    ports:
      - "80:80"
      - "443:443"

networks:
  internal:

volumes:
  geoserver:
  mapstory_static:
  mapstory_media:
  pgadmin:
