---

server_root_dir: "{{ top_project }}"

virtualenv_path: "{{ venv }}"
project_path: "{{ mapstory_geonode }}"

celery_user: mapstory
celery_group: www-data

celery_application_name: mapstory-celery
celery_scripts_dir: "{{ virtualenv_path }}/scripts/celery"
celery_template_file: "{{ celery_application_name }}_start.j2"

celery_log_dir: "/var/log/celery"
celery_log_file: "{{ celery_log_dir }}/{{ celery_application_name }}.log"
celery_num_workers: 6