# demo.mapstory.org configuration
version: '3.1'
services:
  pgadmin:
    ports:
      - "5050:5050"
    secrets:
      - env_db_auth

  elasticsearch:
    ports:
      - "9200:9200"

  rabbitmq:
    secrets:
      - env_rabbitmq_auth
    ports:
      - "15672:15672"

  django:
    env_file:
      - docker/env/demo/public_host.env
      - docker/env/demo/geoserver.env
      - docker/env/demo/mapstory.env
    command: [--collect-static, --init-db, --reindex, --serve]
    secrets:
      - env_db_auth
      - env_email_auth
      - env_geoserver_auth
      - env_rabbitmq_auth
      - env_slack_auth
      - env_social_auth
    volumes:
      - .:/srv/mapstory/
      - site-packages:/usr/local/lib/python2.7/site-packages-copy
    ports:
      - "8000:8000"

  celery:
    env_file:
      - docker/env/demo/public_host.env
      - docker/env/demo/geoserver.env
      - docker/env/demo/mapstory.env
    secrets:
      - env_db_auth
      - env_email_auth
      - env_geoserver_auth
      - env_rabbitmq_auth
      - env_slack_auth
      - env_social_auth
    volumes:
      - .:/srv/mapstory/
      - site-packages:/usr/local/lib/python2.7/site-packages-copy

  geoserver:
    env_file:
      - docker/env/demo/public_host.env
      - docker/env/demo/geoserver.env
    secrets:
      - env_db_auth
      - env_geoserver_auth
    ports:
      - "8080:8080"

  nginx:
    env_file:
      - docker/env/demo/public_host.env
    volumes:
      - .:/srv/mapstory/ # mapstory_static has symlinks to this
      - site-packages:/usr/local/lib/python2.7/site-packages:ro # and this
    secrets:
      - ssl_cert
      - ssl_key

volumes:
  site-packages:

secrets:
  ssl_cert:
    file: ../secrets/ssl_cert
  ssl_key:
    file: ../secrets/ssl_key
  env_db_auth:
    file: ../secrets/env/db_auth
  env_email_auth:
    file: ../secrets/env/email_auth
  env_geoserver_auth:
    file: ../secrets/env/geoserver_auth
  env_rabbitmq_auth:
    file: ../secrets/env/rabbitmq_auth
  env_slack_auth:
    file: ../secrets/env/slack_auth
  env_social_auth:
    file: ../secrets/env/social_auth
