# Dev configuration
version: '3.1'
services:

  postgres:
    image: mdillon/postgis:9.5
    env_file:
      - docker/env/dev/db_auth.env
      - docker/env/dev/postgres.env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      internal:
    expose:
      - "5432"

  pgadmin:
    image: quay.io/mapstory/pgadmin:master
    command: --init-db
    links:
      - postgres
    env_file:
      - docker/env/dev/db_auth.env

  elasticsearch:
    ports:
      - "9200:9200"

  rabbitmq:
    image: quay.io/mapstory/rabbitmq:master
    environment:
      - RABBITMQ_DEFAULT_USER=mapstory
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_DEFAULT_VHOST=mapstory

  django:
    image: quay.io/mapstory/django:master
    links:
      - postgres
    env_file:
      - docker/env/dev/public_host.env
      - docker/env/dev/geoserver.env
      - docker/env/dev/mapstory.env
      - docker/env/dev/db_auth.env
#    command: --init-db --test
    volumes:
      - ./.coveragerc:/srv/mapstory/.coveragerc
      - ./.git:/srv/mapstory/.git
      - ./cover:/srv/mapstory/cover

  celery:
    image: quay.io/mapstory/django:master
    links:
      - postgres
    env_file:
      - docker/env/dev/public_host.env
      - docker/env/dev/geoserver.env
      - docker/env/dev/mapstory.env
      - docker/env/dev/db_auth.env
    environment:
      CELERY_NUM_WORKERS: 1

  django_volumes:
    image: quay.io/mapstory/django:master
    entrypoint: /bin/sh -c "chown -R mapstory:mapstory /var/lib/mapstory && chown -R mapstory:mapstory /srv/mapstory/cover"
    volumes:
      - ./cover:/srv/mapstory/cover

  geoserver:
    links:
      - postgres
    env_file:
      - docker/env/dev/public_host.env
      - docker/env/dev/geoserver.env
      - docker/env/dev/db_auth.env

  nginx:
    image: quay.io/mapstory/nginx:master
    env_file:
      - docker/env/dev/public_host.env
    networks:
      internal:
        aliases:
          - docker
    ports:
      - "80:80"
      - "443:443"

volumes:
  postgres:
