---

- name: dev locale
  action: command sudo update-locale LC_ALL=en_US.UTF-8

- name: set default locale
  become: yes
  lineinfile: dest=/etc/default/locale
    regexp="LC_ALL"
    line="LC_ALL=\"en_US.UTF-8\""

- name: Ensure bash, OpenSSl, and libssl are the latest versions
  apt: name={{ item }} update_cache={{ update_apt_cache }} state=latest
  with_items:
    - bash
    - openssl
    - libssl-dev
    - libssl-doc
  tags: packages

- name: Install base packages
  apt: name={{ item }} update_cache={{ update_apt_cache }} force=yes state=installed
  with_items:
    - build-essential
    - ntp
    - htop
    - git
    - libpq-dev
    - python-dev
    - python-pip
    - python-pycurl
    - python-psycopg2
    - supervisor
    - binutils
    - libproj-dev
    - gdal-bin
    - python-gdal
    - libpng-dev
    - libfreetype6-dev
    - pkg-config
    - libjpeg62
    - libjpeg62-dev
    - libblas-dev
    - liblapack-dev
    - libatlas-base-dev
    - gfortran
    - unzip
    - zip
    - unattended-upgrades
  tags: packages

- name: activate unattended-upgrades
  lineinfile: dest=/etc/apt/apt.conf.d/10periodic line='APT::Periodic::Unattended-Upgrade "1";'
  tags: packages

- name: add auto upgrates
  lineinfile: dest=/etc/apt/apt.conf.d/20auto-upgrades create=yes line='{{item}}'
  tags: unattended
  with_items:
    - 'APT::Periodic::Update-Package-Lists "1";'
    - 'APT::Periodic::Unattended-Upgrade "1";'

- name: Install virtualenv
  pip: name=virtualenv
  tags: packages

- name: Install virtualenv
  pip: name=virtualenvwrapper
  tags: packages
