---

- name: restart nginx
  service: name=nginx state=restarted

- name: reload supervisor
  shell: /usr/bin/supervisorctl reload
  sudo: yes

- name: restart django
  supervisorctl: name=gunicorn-django state=started
  sudo: yes
  notify: check django running
  ignore_errors: True

- name: check django running
  uri: url=http://localhost

- name: init elasticsearch
  command: update-rc.d elasticsearch defaults 95 10
  tags: [elasticsearch]